apiVersion: v1
kind: Pod
metadata: 
  name: client-pod
  labels: 
    component: web
spec: 
  containers: 
    - name: client
      image: wujenny15/ks-multi-client
      ports: 
        - containerPort: 3000
      
